### PR TITLE
Workyworky

### PR DESCRIPTION
**Pull request by sclaridg**

### CODE REVIEW

**Comment by Leslie-C** [comment]
"Check strand" will be a bit more complicated. In real world data, you're going to have more values that just ```0``` and ```16``` in the bitwise FLAG.

**Comment by Leslie-C** [comment]
What if the soft clipping is on the "wrong" side?

**Comment by Leslie-C** [comment]
Don't forget the last part of the assignment:
Determine high level functions
- description
- header
- text examples
- return statement

**Comment by goodez** [comment]
Nice job on your html file. It is well written and thoughtfully organized. I could not find anything that I would change in your code - it is very similar to my layout. In fact, I found it helpful comparing your approach with my own. You made me realize I need to account for strandedness. The functions you provide seem solid.

**Pull request merged**
